### ISSUE TITLE
3.0 and 3.1 tarballs are missing .version files

### ISSUE THREAD

**Issue by AdamWill** [roboptim/roboptim-core#103]
As the comments in `cmake/version.cmake` make very clear, stable release tarballs are supposed to include a `.version` file, as their version cannot be figured out from git metadata because they contain no git metadata.

The 2.0 release tarballs have the `.version` file, but the 3.0 and 3.1 tarballs do not, so when you build from the 3.0 or 3.1 tarballs, the project version is set to `UNKNOWN-dirty`, which shows up in the pkgconfig file and means plugins won't build.

**Comment by bchretien** [comment]
Good catch :+1: That's my bad, I had some issues with the automated tarball generation from the jrl-cmakemodules, and forgot the re-add these.

**Comment by AdamWill** [comment]
This also applies to roboptim-trajectory, and I guess maybe other plugins too; should I file a separate issue or is it not needed? Thanks!

**Comment by bchretien** [comment]
This will be the same for all the `>= 3.0` releases, so this issue should be enough.

**Comment by bchretien** [comment]
Updated releases:

- [x] roboptim-core 3.1
- [ ] roboptim-core-plugin-ipopt 3.1
- [ ] roboptim-core-python 3.1
- [ ] roboptim-trajectory 3.1

Do you really need the 3.0 release too?

**Comment by AdamWill** [comment]
Personally, not at all, I just mentioned it to help you identify where the problem started.

**Comment by bchretien** [comment]
Ok, this is just not as urgent as the latest stable release (3.1). The semi-automated command (from the jrl-cmakemodules) does work as intended, so I'll probably just re-generate the other tarballs while going for lunch tomorrow.

**Comment by bchretien** [comment]
The 3.1 tarballs should be ok now. I'll close this once you confirm that everything is fine.
