### ISSUE TITLE
Why don't you use FIND_PACKAGE(...)?

### ISSUE THREAD

**Issue by phuicy** [roboptim/roboptim-core#107]
In CMAKE you use includes  and  other tools such as ADD_REQUIRED_DEPENDENCY("eigen3 >= 3.2.0") to manage dependencies; instead of the more standard find_package. What is the purpose of this?

**Comment by bchretien** [comment]
We are using our [jrl-cmakemodules](https://github.com/jrl-umi3218/jrl-cmakemodules) that automatically manage pkg-config support (e.g. properly setting compiler flags from dependencies), documentation, pkg-config file generation, etc. Doing things properly in pure CMake is both difficult and extremely verbose. Also, `find_package` relies on `FindXXXXX.cmake` scripts, which are often unreliable or simply unavailable. On the other hand, pkg-config is well supported. You can check the [CMake documentation](https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Piggybacking_on_pkg-config) on the subject.

**Comment by phuicy** [comment]
thanks. Is this true for windows?

**Comment by bchretien** [comment]
Although our code base is mostly used on Linux, pkg-config is also supported on Mac OS X and Windows. For the latter, we've managed to use our CMake modules for different projects built with AppVeyor, with pkg-config support enabled (cf. jrl-umi3218/jrl-travis#28).

**Comment by phuicy** [comment]
thanks
