### ISSUE TITLE
The following tests FAILED (16 31 48 55 )

### ISSUE THREAD

**Issue by ZahraBoroujeni** [roboptim/roboptim-core#116]
I am using 
- ubuntu 14.04. 
- gcc (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3
- eigen3 3.2.0

the package compiled successfully however the `make test`result shows that 4 tests are failed!

```
Total Test time (real) =   3.90 sec

The following tests FAILED:
     16 - problem (Failed)
     31 - result-analyzer (Failed)
     48 - operator-bind (Failed)
     55 - operator-product (Failed)
Errors while running CTest
make: *** [test] Error 8

```

**Comment by bchretien** [comment]
Which version of roboptim-core are you using? (specify the latest commit hash if you're not on a release)

Can you also provide the output of the tests that failed?

**Comment by ZahraBoroujeni** [comment]
roboptim-core, version 3.2-188-gff976-dirty

Error of 16 (problem) and 31(result-analyzer):
```

log4cxx: Could not open file [/home/mi/boroujeni/roboptim-core/tests/log4cxx.xml].
problem: /usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:53: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = int; int Value = 1]: Assertion `v == T(Value)' failed.
unknown location(0): fatal error in "problem<N8roboptim17EigenMatrixSparseE>": signal: SIGABRT (application abort requested)
/home/mi/boroujeni/roboptim-core/tests/problem.cc(93): last checkpoint

*** 1 failure detected in test suite "Master Test Suite"
```

**Comment by bchretien** [comment]
I will need to check with Eigen 3.2.0, this is an old version and we are not testing against it. In the meantime, could you give Eigen 3.2.9 a go? You will need to specify the Eigen include directory when building.

**Comment by bchretien** [comment]
After #117, we increased the minimum required Eigen version, since older versions contain known issues (especially with sparse matrices). I'm closing this since we now expect `Eigen >= 3.2.5`. Let me know if updating Eigen fixed it for you.
