### ISSUE TITLE
Debian/Ubuntu installation command line doesn't work

### ISSUE THREAD

**Issue by Elektron97** [roboptim/roboptim-core#127]
Hi everyone, thank you in advance for your help. I'm trying to install your package, but: `sudo apt-get install libroboptim-core-dev` command doesn't work. The error is:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libroboptim-core-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libroboptim-core-dev' has no installation candidate
```

**Comment by gergondet** [comment]
Hi @Elektron97 

This package has not been actively used/maintained for a while now. The roboptim-core package has been removed from Debian archives (and thus derivatives) a while back.

If you wish to try and use roboptim you can try to build it from source.
