### ISSUE TITLE
Team discussion: gitter or slack?

### ISSUE THREAD

**Issue by bchretien** [roboptim/roboptim-core#87]
We should really start to use that kind of solution, since the pool of users/contributors is increasing, and having to contact different contributors on a per-topic basis to have their thoughts is quite inconvenient for me. With a chat room system that integrates well with GitHub/Travis (i.e. supports their hooks), we may be able to improve our current workflow.

So, question for the developers/contributors: should we go for [gitter](https://gitter.im/) or [slack](https://slack.com/)?

**Comment by thomas-moulard** [comment]
Gitter seems cool, but if someone has a compelling argument I don't mind slack either ˆˆ

**Comment by bchretien** [comment]
I would also say gitter, since the developers seemed nice and reactive when users reported bugs.

**Comment by bchretien** [comment]
Going for gitter.
